
package co.ke.transunion.crbws.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControllerDCImplService", targetNamespace = "http://impl.ws.crbws.transunion.ke.co/", wsdlLocation = "file:/C:/Users/user/Desktop/crb/src/main/resources/dc.xml")
public class ControllerDCImplService
    extends Service
{

    private final static URL CONTROLLERDCIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLLERDCIMPLSERVICE_EXCEPTION;
    private final static QName CONTROLLERDCIMPLSERVICE_QNAME = new QName("http://impl.ws.crbws.transunion.ke.co/", "ControllerDCImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/user/Desktop/crb/src/main/resources/dc.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLLERDCIMPLSERVICE_WSDL_LOCATION = url;
        CONTROLLERDCIMPLSERVICE_EXCEPTION = e;
    }

    public ControllerDCImplService() {
        super(__getWsdlLocation(), CONTROLLERDCIMPLSERVICE_QNAME);
    }

    public ControllerDCImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLLERDCIMPLSERVICE_QNAME, features);
    }

    public ControllerDCImplService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLLERDCIMPLSERVICE_QNAME);
    }

    public ControllerDCImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLLERDCIMPLSERVICE_QNAME, features);
    }

    public ControllerDCImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControllerDCImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControllerDC
     */
    @WebEndpoint(name = "ControllerDCImplPort")
    public ControllerDC getControllerDCImplPort() {
        return super.getPort(new QName("http://impl.ws.crbws.transunion.ke.co/", "ControllerDCImplPort"), ControllerDC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControllerDC
     */
    @WebEndpoint(name = "ControllerDCImplPort")
    public ControllerDC getControllerDCImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.crbws.transunion.ke.co/", "ControllerDCImplPort"), ControllerDC.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLLERDCIMPLSERVICE_EXCEPTION!= null) {
            throw CONTROLLERDCIMPLSERVICE_EXCEPTION;
        }
        return CONTROLLERDCIMPLSERVICE_WSDL_LOCATION;
    }

}
